stages:
  - test
  - build
  - release

Django Tests:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - pythom manage.py test --noinput
  tags:
    - docker

Docker Build:
  stage: build
  image: docker:stable
  service:
    - docker:dind
  script:
    - docker login -u github-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} .
    - cocker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
  tags:
    - docker

Release:
  stage: release
  image: docker:stable
  sevices:
    - docker:dind
  script:
    - docker login -u github-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
    - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
  when: manual
  tags:
    - docker
